name: moto_mitra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  http: ^1.3.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/icons/
    - assets/images/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/icons/MyFlutterApp.ttf

